/* Currently, the plot has many issues including the following:
    - Spaghetti code
    - Plot-Canvas coordinate conversion based on first series only
    - Problematic axes

This stems from the fact that so far I have been learning how raqote works, and also learning how to plot things. I am now a bit more comfortable, and able to do some planning.

A comprehensive rewrite of the underlying plot structure should fix all three. Notably:
    - Have a plotting buffer with the plot-fractional coordinate plot information. i.e. plot_type (e.g. Scatter), plot_data: (e.g. ScatterPoints, scaled to 0.0-1.0 range)
*/

use raqote::DrawTarget;

use crate::{
    colours::ColourPalette,
    plot::renewed_scatter::{ScatterConfig, scatter_plot},
    shapes::Point2d,
};

#[derive(Clone, Copy, Debug)]
pub(crate) enum PlotType {
    Scatter,
    Line,
    Bar,
    Hist,
}

#[derive(Clone, Copy, Debug)]
pub(crate) enum PlotData {
    Point(Point2d),
}

pub trait SeriesData {}

#[derive(Clone, Copy, Debug)]
pub(crate) enum PlotConfig {
    Scatter(ScatterConfig),
}

#[derive(Clone, Copy, Debug)]
pub struct BoundingBox {
    pub xmin: f32,
    pub xmax: f32,
    pub ymin: f32,
    pub ymax: f32,
}

/// General struct to hold information about a certain series
#[derive(Clone)]
pub(crate) struct PlotSeries {
    /// Plot type (scatter, line, bar, hist, etc...)
    pub(crate) plt_type: PlotType,
    /// Plot data normalised to plot extents (0.0-1.0)
    pub(crate) plt_normalised_data: Vec<PlotData>,
    /// Plot config (e.g. colours, markers, etc...)
    pub(crate) plt_config: PlotConfig,
    /// Plot extents [xlo, xhi, ylo, yhi] in data coordinates
    pub(crate) plt_extent: BoundingBox,
}
impl PlotSeries {
    pub(crate) fn plot(
        &self,
        plot: &mut Plot,
        x_scale: f32,
        y_scale: f32,
        x_offset: f32,
        y_offset: f32,
        extents: &BoundingBox,
    ) {
        match self.plt_type {
            PlotType::Scatter => {
                scatter_plot(plot, &self.plt_normalised_data, &self.plt_config, extents)
            }
            PlotType::Line => todo!(),
            PlotType::Bar => todo!(),
            PlotType::Hist => todo!(),
        }
    }
}

pub struct Margins {
    pub top: f32,
    pub left: f32,
    pub right: f32,
    pub bottom: f32,
}

pub struct AxisConfig {
    pub show: bool,
}

/// User-facing plot struct, with canvas dimensions, background colour, etc...
pub struct Plot {
    /// Canvas width (px)
    pub width: f32,
    /// Canvas height (px)
    pub height: f32,
    /// Drawing Canvas
    pub canvas: DrawTarget,
    /// Margins as a fraction of canvas size
    pub margins: Margins,
    /// Axes config information
    pub axes_info: [AxisConfig; 2],
    /// Colour palette
    pub colour_palette: ColourPalette,
    /// Series to draw, these should be generated by the relevant functions, not manually
    pub(crate) series: Vec<PlotSeries>,
    /// The x/y axis extents (min/max)
    pub(crate) axis_extents: Option<BoundingBox>,
}

impl Plot {
    pub fn new(
        width: f32,
        height: f32,
        margins: Margins,
        xaxis: AxisConfig,
        yaxis: AxisConfig,
        palette: ColourPalette,
        axis_extents: Option<BoundingBox>,
    ) -> Self {
        Self {
            width,
            height,
            canvas: DrawTarget::new(width as i32, height as i32),
            margins,
            axes_info: [xaxis, yaxis],
            colour_palette: palette,
            series: Vec::new(),
            axis_extents,
        }
    }

    pub fn draw(&mut self) {
        let plot_bbox: BoundingBox = self.get_plot_bbox();

        if self.axis_extents.is_none() {
            let xmin: f32 = get_plot_extent(&self.series, true, true);
            let xmax: f32 = get_plot_extent(&self.series, true, false);
            let ymin: f32 = get_plot_extent(&self.series, false, true);
            let ymax: f32 = get_plot_extent(&self.series, false, false);

            self.axis_extents = Some(BoundingBox {
                xmin,
                xmax,
                ymin,
                ymax,
            });
        }

        let extents: BoundingBox = self.axis_extents.unwrap();

        for series in self.series.clone() {
            let x_scale: f32 = (extents.xmax - extents.xmin)
                / (series.plt_extent.xmax - series.plt_extent.xmin)
                * (plot_bbox.xmax - plot_bbox.xmin); // TODO: Multiply by plot area width
            let y_scale: f32 = (extents.ymax - extents.ymin)
                / (series.plt_extent.ymax - series.plt_extent.ymin)
                * (plot_bbox.ymax - plot_bbox.ymin);

            let x_offset: f32 = plot_bbox.xmin;
            let y_offset: f32 = plot_bbox.ymax;

            series.plot(self, x_scale, y_scale, x_offset, y_offset, &extents);
        }

        self.draw_axes();
    }

    /// Get the plot area bounding box (in canvas coordinates)
    pub fn get_plot_bbox(&self) -> BoundingBox {
        todo!()
    }

    /// Draw the axes for the plot
    pub fn draw_axes(&mut self) {
        todo!()
    }
}

/// Get the min/max for a given coordinate axis from the plot data (in plot/data coordinates)
fn get_plot_extent(series: &[PlotSeries], x: bool, min: bool) -> f32 {
    let item: &BoundingBox = if min {
        &series
            .iter()
            .min_by(|a, b| {
                if x {
                    a.plt_extent.xmin.partial_cmp(&b.plt_extent.xmin).unwrap()
                } else {
                    a.plt_extent.ymin.partial_cmp(&b.plt_extent.ymin).unwrap()
                }
            })
            .unwrap()
            .plt_extent
    } else {
        &series
            .iter()
            .max_by(|a, b| {
                if x {
                    a.plt_extent.xmax.partial_cmp(&b.plt_extent.xmax).unwrap()
                } else {
                    a.plt_extent.ymax.partial_cmp(&b.plt_extent.ymax).unwrap()
                }
            })
            .unwrap()
            .plt_extent
    };

    match (x, min) {
        (true, true) => item.xmin,
        (true, false) => item.xmax,
        (false, true) => item.ymin,
        (false, false) => item.ymax,
    }
}
